GET http://localhost:8080/users
Accept: application/json

###

POST http://localhost:8080/users
Accept: application/json
Content-Type: application/json

{
   "email": "test@test.org",
   "password": "password"
}
